# Generated by Django 3.1.2 on 2020-10-15 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('avatar', models.ImageField(default='user_profiles/devault_avatar.jpg/', upload_to='user_profiles', verbose_name='Аватарка')),
                ('gender', models.CharField(blank=True, choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address_city', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Баткен', ''), ('Балыкчы', 'Балыкчы'), ('Талас', 'Талас'), ('Джалал-Абад', 'Джалал-Абад')], default='Бишкек', max_length=50)),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('address_optoinaly', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительный адрес')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
