# Generated by Django 3.1.2 on 2020-10-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['name'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
