# Generated by Django 3.1.2 on 2020-10-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0004_auto_20201015_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated',
        ),
    ]
