# Generated by Django 3.1.2 on 2020-11-02 13:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0005_auto_20201015_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='user', editable=False, populate_from='user'),
        ),
    ]
