# Generated by Django 3.1.2 on 2020-10-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addentional_images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images_addentional', verbose_name='Дополнительные фотографии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='/product_images_main/default_main_photo.jpg/', upload_to='product_images_main', verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Текущая цена'),
        ),
    ]
