# Generated by Django 3.1.2 on 2020-10-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201007_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='/product_images_main/default_main_photo.png/', upload_to='product_images_main', verbose_name='Основное фото'),
        ),
    ]
