# Generated by Django 3.1.2 on 2020-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201008_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={'ordering': ['name'], 'verbose_name': 'Характеристики товара', 'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
