# Generated by Django 3.1.2 on 2020-10-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201014_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={'verbose_name': 'Характеристики товара', 'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productcharacteristic',
            name='updated',
        ),
        migrations.AlterField(
            model_name='productcharacteristic',
            name='size',
            field=models.IntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL'), (7, 'XXXL'), (8, 'Все размеры XS - XXXL')], default=8, verbose_name='Размеры'),
        ),
    ]
