# Generated by Django 3.1.2 on 2020-11-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201123_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
