# Generated by Django 3.1.2 on 2020-10-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
