# Generated by Django 3.1.2 on 2020-11-10 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201009_1325'),
        ('order', '0002_auto_20201013_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='updated',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_list', to='order.orderlist'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='order_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='order.orderlist'),
        ),
    ]
