# Generated by Django 3.1.2 on 2020-11-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201110_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderList',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_list',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='order_list',
            new_name='order',
        ),
    ]
